### ISSUE TITLE
error:  invalid character 'G' looking for beginning of value

### ISSUE THREAD

**Issue by bendodd** [jthomas/copyenv#5] opened 2016-05-23 17:04 UTC
I'm getting this error when attempting to use the plugin on a mac with various VCAP_SERVICES configs

```
error:  invalid character 'G' looking for beginning of value
```

```
$ cf -v
cf version 6.17.0+5d0be0a-2016-04-15
```

**Comment by jthomas** [comment] 2016-05-26 17:20
Hello. 

Are you able to provide me with one of your sample VCAP_SERVICES (scrubbing out the confidential details)?

**Comment by bendodd** [comment] 2016-05-27 09:13
```
$ cf -v
cf version 6.17.0+5d0be0a-2016-04-15

$ go get github.com/jthomas/copyenv
$ cf install-plugin $GOPATH/bin/copyenv
...
OK
Plugin copyenv v1.0.0 successfully installed.
```

I used the ruby app in here:
https://github.com/cloudfoundry-incubator/cf-smoke-tests.git - /assets/ruby_simple

```
Using PWS:
$ cf create-user-provided-service service-mysql-1 -p "{\"hostname\":\"foo.com\",\"name\":\"foo\",\"username\":\"foo\",\"password\":\"foo\"}"
$ cf bind-service cf-smoke-tests-ruby-simple service-mysql-1
$ cf a
Getting apps in org [PRIVATE DATA HIDDEN] / space [PRIVATE DATA HIDDEN] as [PRIVATE DATA HIDDEN]...
OK
name                         requested state   instances   memory   disk   urls
cf-smoke-tests-ruby-simple   started           1/1         56M      1G     cf-smoke-tests-ruby-simple.cfapps.io
```

```
$ CF_TRACE=true cf copyenv cf-smoke-tests-ruby-simple

REQUEST: [2016-05-27T10:07:57+01:00]
GET /v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/apps?q=name%3Acf-smoke-tests-ruby-simple&inline-relations-depth=1 HTTP/1.1
Host: api.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.17.0+5d0be0a / darwin



RESPONSE: [2016-05-27T10:07:58+01:00]
HTTP/1.1 200 OK
Content-Length: 6025
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 27 May 2016 09:07:59 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: d11149b9-0653-46c5-648f-f1840c361f09
X-Vcap-Request-Id: d11149b9-0653-46c5-648f-f1840c361f09::e43051a6-a6d6-427b-aac3-f784bc6fbff5

{
  "total_results": 1,
  "total_pages": 1,
  "prev_url": null,
  "next_url": null,
  "resources": [
    {
      "metadata": {
        "guid": "6706a469-3309-4d77-ac0b-47cf4eb68f03",
        "url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03",
        "created_at": "2016-05-27T09:03:35Z",
        "updated_at": "2016-05-27T09:07:25Z"
      },
      "entity": {
        "name": "cf-smoke-tests-ruby-simple",
        "production": false,
        "space_guid": "8d812f96-8d15-4f5b-bdaf-614f2084812c",
        "stack_guid": "86205f38-84fc-4bc2-b2b8-af7f55669f04",
        "buildpack": null,
        "detected_buildpack": "ruby 1.6.16",
        "environment_json": {

        },
        "memory": 56,
        "instances": 1,
        "disk_quota": 1024,
        "state": "STARTED",
        "version": "3dd77e0a-07dc-4920-a088-b5d05455683e",
        "command": null,
        "console": false,
        "debug": null,
        "staging_task_id": "0048e7e6b41c47fc958fe6788926b36f",
        "package_state": "STAGED",
        "health_check_type": "port",
        "health_check_timeout": null,
        "staging_failed_reason": null,
        "staging_failed_description": null,
        "diego": true,
        "docker_image": null,
        "package_updated_at": "2016-05-27T09:04:08Z",
        "detected_start_command": "bundle exec rackup config.ru -p $PORT",
        "enable_ssh": true,
        "docker_credentials_json": {
          "redacted_message": "[PRIVATE DATA HIDDEN]"
        },
        "ports": [
          8080
        ],
        "space_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c",
        "space": {
          "metadata": {
            "guid": "8d812f96-8d15-4f5b-bdaf-614f2084812c",
            "url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c",
            "created_at": "2016-03-03T10:32:10Z",
            "updated_at": null
          },
          "entity": {
            "name": "development",
            "organization_guid": "7627da8f-6fee-426c-b22a-ce7575ef8b29",
            "space_quota_definition_guid": null,
            "allow_ssh": true,
            "organization_url": "/v2/organizations/7627da8f-6fee-426c-b22a-ce7575ef8b29",
            "developers_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/developers",
            "managers_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/managers",
            "auditors_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/auditors",
            "apps_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/apps",
            "routes_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/routes",
            "domains_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/domains",
            "service_instances_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/service_instances",
            "app_events_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/app_events",
            "events_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/events",
            "security_groups_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c/security_groups"
          }
        },
        "stack_url": "/v2/stacks/86205f38-84fc-4bc2-b2b8-af7f55669f04",
        "stack": {
          "metadata": {
            "guid": "86205f38-84fc-4bc2-b2b8-af7f55669f04",
            "url": "/v2/stacks/86205f38-84fc-4bc2-b2b8-af7f55669f04",
            "created_at": "2015-03-04T18:58:42Z",
            "updated_at": null
          },
          "entity": {
            "name": "cflinuxfs2",
            "description": "Cloud Foundry Linux-based filesystem"
          }
        },
        "routes_url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03/routes",
        "routes": [
          {
            "metadata": {
              "guid": "00bb9dcc-7f44-4dea-87b8-72dfcbaea53e",
              "url": "/v2/routes/00bb9dcc-7f44-4dea-87b8-72dfcbaea53e",
              "created_at": "2016-05-27T09:03:37Z",
              "updated_at": null
            },
            "entity": {
              "host": "cf-smoke-tests-ruby-simple",
              "path": "",
              "domain_guid": "fb6bd89f-2ed9-49d4-9ad1-97951a573135",
              "space_guid": "8d812f96-8d15-4f5b-bdaf-614f2084812c",
              "service_instance_guid": null,
              "port": null,
              "domain_url": "/v2/domains/fb6bd89f-2ed9-49d4-9ad1-97951a573135",
              "space_url": "/v2/spaces/8d812f96-8d15-4f5b-bdaf-614f2084812c",
              "apps_url": "/v2/routes/00bb9dcc-7f44-4dea-87b8-72dfcbaea53e/apps",
              "route_mappings_url": "/v2/routes/00bb9dcc-7f44-4dea-87b8-72dfcbaea53e/route_mappings"
            }
          }
        ],
        "events_url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03/events",
        "service_bindings_url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03/service_bindings",
        "service_bindings": [
          {
            "metadata": {
              "guid": "bf89cfa5-c039-43c2-9ee0-5f159f836f67",
              "url": "/v2/service_bindings/bf89cfa5-c039-43c2-9ee0-5f159f836f67",
              "created_at": "2016-05-27T09:07:05Z",
              "updated_at": null
            },
            "entity": {
              "app_guid": "6706a469-3309-4d77-ac0b-47cf4eb68f03",
              "service_instance_guid": "378aab23-4cb6-45f7-acc2-c379856604dd",
              "credentials": {
                "hostname": "foo.com",
                "name": "foo",
                "password":"[PRIVATE DATA HIDDEN]",
                "username": "foo"
              },
              "binding_options": {

              },
              "gateway_data": null,
              "gateway_name": "",
              "syslog_drain_url": "",
              "volume_mounts": [

              ],
              "app_url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03",
              "service_instance_url": "/v2/user_provided_service_instances/378aab23-4cb6-45f7-acc2-c379856604dd"
            }
          }
        ],
        "route_mappings_url": "/v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03/route_mappings"
      }
    }
  ]
}

REQUEST: [2016-05-27T10:07:58+01:00]
GET /v2/apps/6706a469-3309-4d77-ac0b-47cf4eb68f03/env HTTP/1.1
Host: api.run.pivotal.io
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: go-cli 6.17.0+5d0be0a / darwin



RESPONSE: [2016-05-27T10:07:58+01:00]
HTTP/1.1 200 OK
Content-Length: 1218
Connection: keep-alive
Content-Type: application/json;charset=utf-8
Date: Fri, 27 May 2016 09:07:59 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 63a93355-8bb9-4a80-7eb0-089497ab8cd0
X-Vcap-Request-Id: 63a93355-8bb9-4a80-7eb0-089497ab8cd0::338b3ba2-762b-4f1c-b0d6-1b0cde00b904

{
  "staging_env_json": {

  },
  "running_env_json": {

  },
  "environment_json": {

  },
  "system_env_json": {
    "VCAP_SERVICES": {
      "user-provided": [
        {
          "credentials": {
            "hostname": "foo.com",
            "name": "foo",
            "password":"[PRIVATE DATA HIDDEN]",
            "username": "foo"
          },
          "syslog_drain_url": "",
          "label": "user-provided",
          "name": "service-mysql-1",
          "tags": [

          ]
        }
      ]
    }
  },
  "application_env_json": {
    "VCAP_APPLICATION": {
      "limits": {
        "fds": 16384,
        "mem": 56,
        "disk": 1024
      },
      "application_name": "cf-smoke-tests-ruby-simple",
      "application_uris": [
        "cf-smoke-tests-ruby-simple.cfapps.io"
      ],
      "name": "cf-smoke-tests-ruby-simple",
      "space_name": "development",
      "space_id": "8d812f96-8d15-4f5b-bdaf-614f2084812c",
      "uris": [
        "cf-smoke-tests-ruby-simple.cfapps.io"
      ],
      "users": null,
      "version": "3dd77e0a-07dc-4920-a088-b5d05455683e",
      "application_version": "3dd77e0a-07dc-4920-a088-b5d05455683e",
      "application_id": "6706a469-3309-4d77-ac0b-47cf4eb68f03"
    }
  }
}
error:  invalid character 'G' looking for beginning of value
```

I hope this is useful @jthomas - let me know if I can help further?

**Comment by jthomas** [comment] 2016-06-13 10:39
Hey, sorry was away on vacation! 
That information is great, I'll debug it and get back to you.

**Comment by jthomas** [comment] 2016-06-23 12:03
This is due to a regression in the CF CLI: https://github.com/cloudfoundry/cli/issues/866

Once this issue is resolved upstream, you'll need to update your CLI and it should all be fixed.

**Comment by lorentzlasson** [comment] 2016-07-04 14:52
Have issues using cf v `6.20.0+25b1961-2016-06-29` which is said to have fixed the problem, but I get this error message instead now `error:  invalid character ':' after top-level value`.

I'm also using osx

**Comment by koushikmgit** [comment] 2016-09-08 06:04
hello, I am also getting "invalid character 'G' looking for beginning of value" error during using the copyenv plug-in. I am using cf cli version 6.17 at my end. Is that issue really resolved at cf cli 6.20 ?

**Comment by jthomas** [comment] 2016-09-08 08:31
Hello all, 

I'm still working on a fix for this. I hope to resolve this soon, will update the ticket when it's complete.

**Comment by koushikmgit** [comment] 2016-09-08 08:32
Thanks for your comments. waiting for your fix.

**Comment by jthomas** [comment] 2016-09-09 10:34
I've fixed the bug 😎.
There's a PR open with the plugin repository to release the new version. 
https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/81
If you still have issues after installing the new version, open a new issue.

**Closed as completed by jthomas** 2016-09-09 10:34 UTC
